/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;

import DAO.ChitietDattruocDAO;
import DAO.DVDDAO;
import DAO.TieudeDAO;
import Entity.ChitietDattruoc;
import Entity.DVD;
import Entity.Tieude;

/**
 *
 * @author Minh Hau
 */
public class BaocaoveDiaGD extends javax.swing.JFrame {
	TieudeDAO tddao = new TieudeDAO();
	DVDDAO dvddao = new DVDDAO();
	ChitietDattruocDAO ctdtdao =new ChitietDattruocDAO();

    /**
     * Creates new form Clerk
     */
    public BaocaoveDiaGD() {
        initComponents();
        btnQuaylai.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				BaocaoveDiaGD.this.setVisible(false);
				
			}
		});
        btnTTCoban.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				TTCoban();
				
			}
		});
        btnTongdia.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				tongsoBansaodangco();
				
			}
		});
        btnDTXuly.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				soluongDattruocchoXuly();
				
			}
		});
    }
    public void TTCoban() {
    	try {
			List<Tieude> dstd = tddao.getAllTieude();
			List<DVD> dsdvd = dvddao.getAllDVD();
			int soluongdvd = dsdvd.size();
			int tongsltd = dstd.size();
			int sltieudephim=0;
			int sltieudegame=0;
			for (int i = 0; i < dstd.size(); i++) {
				if(dstd.get(i).getLoaiDVD().equalsIgnoreCase("Phim")) {
					sltieudephim++;
				}else {
					sltieudegame++;
				}
			}
			lbTT1.setText("Tống số lượng tiêu đề: "+tongsltd);
			lbTT2.setText("Tống số lượng DVD: "+soluongdvd);
			lbTT3.setText("Tống số lượng tiêu đề theo thể loại phim: "+sltieudephim);
			lbTT4.setText("Tống số lượng tiêu đề theo thể loại game: "+sltieudegame);
		
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
    public void tongsoBansaodangco() {
    	List<DVD> dsdvd;
		try {
			dsdvd = dvddao.getAllDVD();
			int soluongdvd = dsdvd.size();
			int slbsaoDathue =0;
			int slbsaoDanggiu =0;
			int slbsaoTrongkho =0;
			for (int i = 0; i < dsdvd.size(); i++) {
				if(dsdvd.get(i).getTrangthai().equalsIgnoreCase("Đã được thuê")) {
					slbsaoDathue++;
				}else if(dsdvd.get(i).getTrangthai().equalsIgnoreCase("Đang giữ")){
					slbsaoDanggiu++;
				}else {
					slbsaoTrongkho++;
				}
			}
			lbTT1.setText("Tống số lượng bản sao: "+soluongdvd);
			lbTT2.setText("Tống số lượng bản sao đã được thuê: "+slbsaoDathue);
			lbTT3.setText("Tống số lượng bản sao đang giữ: "+slbsaoDanggiu);
			lbTT4.setText("Tống số lượng bản sao hiện trong kho: "+slbsaoTrongkho);
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
    }
    public void soluongDattruocchoXuly() {
    	try {
			List<ChitietDattruoc> dsctdt = ctdtdao.getAllChitietDattruoc();
			int tsCTDT = dsctdt.size();
			int tsDTchoXL=0;
			for (int i = 0; i < dsctdt.size(); i++) {
				if(dsctdt.get(i).getTrangthai().equalsIgnoreCase("Đang đặt")) {
					tsDTchoXL++;
				}
			}
			lbTT1.setText("Tống số lượng đặt trước: "+tsCTDT);
			lbTT2.setText("Tống số lượng đặt trước đang chờ xử lý: "+tsDTchoXL);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnChinh = new javax.swing.JPanel();
        lbTieude = new javax.swing.JLabel();
        btnQuaylai = new javax.swing.JLabel();
        btnTTCoban = new javax.swing.JButton();
        btnTongdia = new javax.swing.JButton();
        lbTT1 = new javax.swing.JLabel();
        lbTT3 = new javax.swing.JLabel();
        lbTT2 = new javax.swing.JLabel();
        lbTT5 = new javax.swing.JLabel();
        lbTT4 = new javax.swing.JLabel();
        lbTT6 = new javax.swing.JLabel();
        lbTT8 = new javax.swing.JLabel();
        lbTT7 = new javax.swing.JLabel();
        btnDTXuly = new javax.swing.JButton();
        setTitle("Phần mềm cho thuê đĩa");
     	//dat cua so giua man hinh
        setLocationRelativeTo(null);
        //khong cho phong to cua so
        setResizable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTieude.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbTieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTieude.setText("BÁO CÁO VỀ BẢN SAO");

        btnQuaylai.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        btnQuaylai.setForeground(new java.awt.Color(204, 0, 0));
        btnQuaylai.setText("Quay lại");

        btnTTCoban.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTTCoban.setText("Thông tin cơ bản");
        btnTTCoban.setPreferredSize(new java.awt.Dimension(220, 100));

        btnTongdia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTongdia.setText("Tổng số bản sảo đang có");
        btnTongdia.setPreferredSize(new java.awt.Dimension(220, 100));

        lbTT1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        lbTT3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        lbTT2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        lbTT5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        lbTT4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        lbTT6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        lbTT8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        lbTT7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N

        btnDTXuly.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDTXuly.setText("Số đặt trước chờ xử lý");
        btnDTXuly.setPreferredSize(new java.awt.Dimension(220, 100));

        javax.swing.GroupLayout pnChinhLayout = new javax.swing.GroupLayout(pnChinh);
        pnChinh.setLayout(pnChinhLayout);
        pnChinhLayout.setHorizontalGroup(
            pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChinhLayout.createSequentialGroup()
                .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChinhLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnQuaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnChinhLayout.createSequentialGroup()
                        .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnChinhLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnTTCoban, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnChinhLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDTXuly, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnChinhLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnTongdia, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71)
                        .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTT3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTT5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTT4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTT8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(138, 138, 138))
            .addGroup(pnChinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTieude, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnChinhLayout.createSequentialGroup()
                    .addGap(322, 322, 322)
                    .addComponent(lbTT6, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addGap(128, 128, 128)))
            .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnChinhLayout.createSequentialGroup()
                    .addGap(322, 322, 322)
                    .addComponent(lbTT7, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addGap(128, 128, 128)))
        );
        pnChinhLayout.setVerticalGroup(
            pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChinhLayout.createSequentialGroup()
                .addComponent(lbTieude, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnChinhLayout.createSequentialGroup()
                        .addComponent(btnTTCoban, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnTongdia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnChinhLayout.createSequentialGroup()
                        .addComponent(lbTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbTT2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbTT3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChinhLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbTT4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbTT5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                        .addComponent(lbTT8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(pnChinhLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnDTXuly, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuaylai)
                        .addContainerGap())))
            .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChinhLayout.createSequentialGroup()
                    .addContainerGap(385, Short.MAX_VALUE)
                    .addComponent(lbTT6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(143, 143, 143)))
            .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChinhLayout.createSequentialGroup()
                    .addContainerGap(446, Short.MAX_VALUE)
                    .addComponent(lbTT7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(82, 82, 82)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaocaoveDiaGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaocaoveDiaGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaocaoveDiaGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaocaoveDiaGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaocaoveDiaGD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnDTXuly;
    private javax.swing.JLabel btnQuaylai;
    private javax.swing.JButton btnTTCoban;
    private javax.swing.JButton btnTongdia;
    private javax.swing.JLabel lbTT1;
    private javax.swing.JLabel lbTT2;
    private javax.swing.JLabel lbTT3;
    private javax.swing.JLabel lbTT4;
    private javax.swing.JLabel lbTT5;
    private javax.swing.JLabel lbTT6;
    private javax.swing.JLabel lbTT7;
    private javax.swing.JLabel lbTT8;
    private javax.swing.JLabel lbTieude;
    private javax.swing.JPanel pnChinh;
    // End of variables declaration                
}
