/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author Minh Hau
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
        btnDangxuat.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				GDDangnhap dngd = new GDDangnhap();
				Manager.this.setVisible(false);
				dngd.setVisible(true);
				
			}
		});
		btnThemtieude.addActionListener(new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						ThemtieudeGD GDSuaLK = new ThemtieudeGD();
				        GDSuaLK.setVisible(true);
					}
				});
		btnXoatieude.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				XoatieudeGD GDSuaLK = new XoatieudeGD();
		        GDSuaLK.setVisible(true);
			}
		});
		btnXoaKH.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				XoaKhachhangGD GDSuaLK = new XoaKhachhangGD();
		        GDSuaLK.setVisible(true);
			}	
		});
		
		btnThemDVD.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				ThemDVDGD GDSuaLK = new ThemDVDGD();
		        GDSuaLK.setVisible(true);
			}
		});
		
		btnHuyphitrehan.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				HuyphiTrehenGD GDSuaLK = new HuyphiTrehenGD();
				 GDSuaLK.setVisible(true);
			}
		});
		btnXoaDVD.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				XoaDVDGD GDSuaLK = new XoaDVDGD();
		        GDSuaLK.setVisible(true);
			}
		});
		//bc ve bản sao
		btnBaocaophitrehan.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				BaocaoveDiaGD bcgd = new BaocaoveDiaGD();
				bcgd.setVisible(true);
			}
		});
		//bc ve Khach hang
		btnBaocaotieude.addActionListener(new ActionListener() {
					
			@Override
			public void actionPerformed(ActionEvent e) {
				BaocaoveKHGD bcgd = new BaocaoveKHGD();
				bcgd.setVisible(true);
			}
		});
		btnDatphitrehan.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				DatphitrehanGD GDSuaLK = new DatphitrehanGD();
		        GDSuaLK.setVisible(true);
			}
		});
		btnDatgiathue.addActionListener(new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						DatgiaThueGD GDSuaLK = new DatgiaThueGD();
				        GDSuaLK.setVisible(true);
					}
				});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
     // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnChinh = new javax.swing.JPanel();
        lbTieude = new javax.swing.JLabel();
        btnThemtieude = new javax.swing.JButton();
        btnXoaKH = new javax.swing.JButton();
        btnXoatieude = new javax.swing.JButton();
        btnThemDVD = new javax.swing.JButton();
        btnXoaDVD = new javax.swing.JButton();
        btnHuyphitrehan = new javax.swing.JButton();
        btnBaocaophitrehan = new javax.swing.JButton();
        btnBaocaotieude = new javax.swing.JButton();
        btnDatphitrehan = new javax.swing.JButton();
        btnDatgiathue = new javax.swing.JButton();
        btnDangxuat = new javax.swing.JLabel();
        setTitle("Phần mềm cho thuê đĩa");
     	//dat cua so giua man hinh
        setLocationRelativeTo(null);
        //khong cho phong to cua so
        setResizable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTieude.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbTieude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTieude.setText("PHẦN MỀM CHO THUÊ ĐĨA");

        btnThemtieude.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\XayDungPM\\XDPMDemo\\icon\\title.png")); // NOI18N
        btnThemtieude.setText("Thêm tiêu đề");
        btnThemtieude.setPreferredSize(new java.awt.Dimension(220, 100));

        btnXoaKH.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\XayDungPM\\XDPMDemo\\icon\\delete-account.png")); // NOI18N
        btnXoaKH.setText("Xóa khách hàng");
        btnXoaKH.setToolTipText("");
        btnXoaKH.setPreferredSize(new java.awt.Dimension(220, 100));

        btnXoatieude.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\XayDungPM\\XDPMDemo\\icon\\delete.png")); // NOI18N
        btnXoatieude.setText("Xóa tiêu đề");
        btnXoatieude.setToolTipText("");
        btnXoatieude.setPreferredSize(new java.awt.Dimension(220, 100));

        btnThemDVD.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\XayDungPM\\XDPMDemo\\icon\\dvd.png")); // NOI18N
        btnThemDVD.setText("Thêm DVD");
        btnThemDVD.setToolTipText("");
        btnThemDVD.setPreferredSize(new java.awt.Dimension(220, 100));

        btnXoaDVD.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\XayDungPM\\XDPMDemo\\icon\\delete (1).png")); // NOI18N
        btnXoaDVD.setText("Xóa DVD");
        btnXoaDVD.setToolTipText("");
        btnXoaDVD.setPreferredSize(new java.awt.Dimension(220, 100));

        btnHuyphitrehan.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\XayDungPM\\XDPMDemo\\icon\\tag.png")); // NOI18N
        btnHuyphitrehan.setText("Hủy phí trễ hạn");
        btnHuyphitrehan.setToolTipText("");
        btnHuyphitrehan.setPreferredSize(new java.awt.Dimension(220, 100));

        btnBaocaophitrehan.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\XayDungPM\\XDPMDemo\\icon\\business-report.png")); // NOI18N
        btnBaocaophitrehan.setText("Báo cáo về bản sao");
        btnBaocaophitrehan.setToolTipText("");
        btnBaocaophitrehan.setPreferredSize(new java.awt.Dimension(220, 100));

        btnBaocaotieude.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\XayDungPM\\XDPMDemo\\icon\\report.png")); // NOI18N
        btnBaocaotieude.setText("Báo cáo về khách hàng");
        btnBaocaotieude.setPreferredSize(new java.awt.Dimension(220, 100));

        btnDatphitrehan.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\XayDungPM\\XDPMDemo\\icon\\fees.png")); // NOI18N
        btnDatphitrehan.setText("Đặt phí trễ hạn");
        btnDatphitrehan.setToolTipText("");
        btnDatphitrehan.setPreferredSize(new java.awt.Dimension(220, 100));

        btnDatgiathue.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\XayDungPM\\XDPMDemo\\icon\\tag (1).png")); // NOI18N
        btnDatgiathue.setText("Đặt giá thuê");
        btnDatgiathue.setToolTipText("");
        btnDatgiathue.setPreferredSize(new java.awt.Dimension(220, 100));

        btnDangxuat.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        btnDangxuat.setForeground(new java.awt.Color(204, 0, 0));
        btnDangxuat.setText("Đăng xuất");

        javax.swing.GroupLayout pnChinhLayout = new javax.swing.GroupLayout(pnChinh);
        pnChinh.setLayout(pnChinhLayout);
        pnChinhLayout.setHorizontalGroup(
            pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChinhLayout.createSequentialGroup()
                .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChinhLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTieude, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE))
                    .addGroup(pnChinhLayout.createSequentialGroup()
                        .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnChinhLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnChinhLayout.createSequentialGroup()
                                        .addComponent(btnThemtieude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXoatieude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXoaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnThemDVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnChinhLayout.createSequentialGroup()
                                        .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnBaocaotieude, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnBaocaophitrehan, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnChinhLayout.createSequentialGroup()
                                                .addComponent(btnHuyphitrehan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnXoaDVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnChinhLayout.createSequentialGroup()
                                                .addComponent(btnDatgiathue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnDatphitrehan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(pnChinhLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnChinhLayout.setVerticalGroup(
            pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChinhLayout.createSequentialGroup()
                .addComponent(lbTieude, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThemtieude, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoatieude, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThemDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoaDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHuyphitrehan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBaocaophitrehan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaocaotieude, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatphitrehan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatgiathue, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(btnDangxuat)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBaocaophitrehan;
    private javax.swing.JButton btnBaocaotieude;
    private javax.swing.JLabel btnDangxuat;
    private javax.swing.JButton btnDatgiathue;
    private javax.swing.JButton btnDatphitrehan;
    private javax.swing.JButton btnHuyphitrehan;
    private javax.swing.JButton btnThemDVD;
    private javax.swing.JButton btnThemtieude;
    private javax.swing.JButton btnXoaDVD;
    private javax.swing.JButton btnXoaKH;
    private javax.swing.JButton btnXoatieude;
    private javax.swing.JLabel lbTieude;
    private javax.swing.JPanel pnChinh;
    // End of variables declaration                   
}
